apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tutorial-server
    app.kubernetes.io/instance: argocd-tutorial
  name: tutorial-server
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tutorial-server
  template:
    metadata:
      labels:
        app: tutorial-server
    spec:
      containers:
        - image: 'nginx:latest'
#        - image: 'ghcr.io/misw-4301-desarrollo-apps-en-la-nube/argocd-tutorial:3.0'
          imagePullPolicy: Always
          name: tutorial-server
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
